# Generated by Django 2.0.13 on 2023-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('Mobile_number', models.IntegerField(max_length=10)),
                ('Account_Number', models.IntegerField(max_length=10)),
                ('IFSC_code', models.TextField(max_length=10)),
                ('Branch_address', models.TextField(max_length=100)),
                ('passbook_Image', models.ImageField(upload_to='SG/')),
            ],
        ),
    ]
