# Generated by Django 2.0.13 on 2023-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclass',
            name='Account_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='Branch_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='IFSC_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='Mobile_number',
            field=models.IntegerField(),
        ),
    ]
